---
AWSTemplateFormatVersion: 2010-09-09

Resources:

    kms:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            TemplateURL: https://test-v1-etl-serverless-public-bucket.s3.us-east-1.amazonaws.com/template-kms.yml # valor original del parametro: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-kms.yml

    s3:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: [kms]
        Properties:
            TemplateURL: https://test-v1-etl-serverless-public-bucket.s3.us-east-1.amazonaws.com/template-s3.yml
            Parameters:
                S3KMSKey: !GetAtt kms.Outputs.kmss3

    iam:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: 
            - kms
            - s3
        Properties:
            TemplateURL: https://test-v1-etl-serverless-public-bucket.s3.us-east-1.amazonaws.com/template-iam.yml
            Parameters:
                S3KMSKey: !GetAtt kms.Outputs.kmsarn
                Bucketdataconsume: !GetAtt s3.Outputs.Bucketdata

    lambdas:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: iam
        Properties:
            TemplateURL: https://test-v1-etl-serverless-public-bucket.s3.us-east-1.amazonaws.com/template-lambdas.yml
            Parameters:
                LambdaExecutionRole: !GetAtt iam.Outputs.LambdaExecutionRolearn

    glue:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: 
            - iam
            - s3
        Properties:
            TemplateURL: https://test-v1-etl-serverless-public-bucket.s3.us-east-1.amazonaws.com/template-glue.yaml
            Parameters:
                roleglue: !GetAtt iam.Outputs.glueExecutionRolearn

    step:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: 
            - iam
            - lambdas
            - glue
        Properties:
            TemplateURL: https://test-v1-etl-serverless-public-bucket.s3.us-east-1.amazonaws.com/template-step.yaml
            Parameters:
                StepExecutionRole: !GetAtt iam.Outputs.stepExecutionRolearn

    eventbridge:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: 
            - iam
            - step
            - lambdas
        Properties:
            TemplateURL: https://test-v1-etl-serverless-public-bucket.s3.us-east-1.amazonaws.com/template-eventbridge.yaml
            Parameters:
                ArnStepFunction: !GetAtt step.Outputs.ArnStepFunction
                RoleEvent: !GetAtt iam.Outputs.EventBridgeRolearn
    #ec2:
        #Type: "AWS::CloudFormation::Stack"
        #Properties:
            #TemplateURL: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-ec2.yaml
