AWSTemplateFormatVersion: '2010-09-09'
Description: iam roles.

Parameters:
    roleglue:
        Type: String

Resources:
  GlueLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws-glue/jobs/output"

  rGlueJobTransforma:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: 3
        ScriptLocation: "s3://test-v1-etl-serverless-glue-code/transform.py" # Valor original del parametro: s3://awdataclouders-s3-glue-code-2/transform.py
      GlueVersion: "4.0"
      DefaultArguments:
        "--job-language": "python"
        "--job-bookmark-option": "job-bookmark-enable"
        "--spark-event-logs-path": "s3://test-v1-etl-serverless-glue-code/" # Valor original del parametro: s3://awdataclouders-s3-glue-code-2/
        "--enable-spark-ui": "true"
        "--enable-glue-datacatalog": "true"  
        "--enable-metrics": "true"           
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 1
      Name: GlueTransform
      Role: !Ref roleglue
      WorkerType: Standard
      NumberOfWorkers: 1

  rGlueJobDataQuality:
      Type: AWS::Glue::Job
      Properties:
        Command:
          Name: glueetl
          PythonVersion: 3
          ScriptLocation: "s3://test-v1-etl-serverless-glue-code/quality.py" # Valor original del parametro: s3://awdataclouders-s3-glue-code-2/quality.py
        GlueVersion: "4.0"
        DefaultArguments: 
          "--job-language": "python"
          "--job-bookmark-option": "job-bookmark-enable"
          "--spark-event-logs-path": "s3://test-v1-etl-serverless-glue-code/" # Valor original del parametro: s3://awdataclouders-s3-glue-code-2/
          "--enable-spark-ui": "true"
          "--enable-glue-datacatalog": "true"  
          "--enable-metrics": "true" 
        ExecutionProperty:
          MaxConcurrentRuns: 2
        MaxRetries: 1
        Name: GlueQuality
        Role: !Ref roleglue
        WorkerType: Standard
        NumberOfWorkers: 1
